apiVersion: batch/v1
kind: Job
metadata:
  name: debug-postgres-migrations
  namespace: airflow
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: mydnsrandomnamedafj.azurecr.io/airflow:2.9.3-custom
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-metadata
              key: connection
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-metadata
              key: connection
        command: ["airflow", "db", "upgrade"]
      restartPolicy: Never
