apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: airflow
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://airflowkeys.vault.azure.net/"
      serviceAccountRef:
        name: airflow